# Generated by Django 6.0.7 on 2026-08-03 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Clínica Odontológica Dra. Paula Muñoz', max_length=120, verbose_name='nombre')),
                ('odontologa', models.CharField(default='Dra. Paula Muñoz', max_length=120, verbose_name='odontóloga')),
                ('direccion', models.CharField(max_length=160, verbose_name='dirección')),
                ('consultorio', models.CharField(blank=True, max_length=60, verbose_name='consultorio')),
                ('ciudad', models.CharField(default='Envigado', max_length=80, verbose_name='ciudad')),
                ('departamento', models.CharField(default='Antioquia', max_length=80, verbose_name='departamento')),
                ('whatsapp', models.CharField(help_text='Solo dígitos, con indicativo del país. Ejemplo: 573007711549', max_length=20, verbose_name='WhatsApp')),
                ('telefono_fijo', models.CharField(blank=True, max_length=30, verbose_name='teléfono fijo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('dominio', models.CharField(blank=True, help_text='Dominio público, sin https://. Se usa en las etiquetas para buscadores.', max_length=120, verbose_name='dominio')),
                ('presentacion', models.TextField(blank=True, help_text='Los párrafos de «La clínica». Separa cada párrafo con una línea en blanco.', verbose_name='presentación')),
            ],
            options={
                'verbose_name': 'datos de la clínica',
                'verbose_name_plural': 'datos de la clínica',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='día')),
                ('abre', models.TimeField(blank=True, null=True, verbose_name='abre')),
                ('cierra', models.TimeField(blank=True, null=True, verbose_name='cierra')),
                ('cerrado', models.BooleanField(default=False, verbose_name='cerrado')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='testimonio')),
                ('autor', models.CharField(help_text='Como aparece en la reseña. Ejemplo: Juan T.', max_length=80, verbose_name='autor')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': 'testimonios',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('zona', models.CharField(blank=True, choices=[('incisivos', 'Incisivos'), ('caninos', 'Caninos'), ('premolares', 'Premolares'), ('molares', 'Molares'), ('cordales', 'Cordales'), ('encia', 'Encía')], help_text='Déjalo en blanco si el tratamiento no se ubica en un diente (odontopediatría, sedación). Cada zona admite un solo tratamiento.', max_length=20, verbose_name='zona de la arcada')),
                ('zona_detalle', models.CharField(blank=True, help_text='Lo que se lee bajo el nombre. Si se deja vacío, se usa el nombre de la zona.', max_length=80, verbose_name='texto de la zona')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'tratamiento',
                'verbose_name_plural': 'tratamientos',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('zona', ''), _negated=True), fields=('zona',), name='una_zona_un_tratamiento')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=40, verbose_name='teléfono')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='recibida')),
                ('atendida', models.BooleanField(default=False, verbose_name='atendida')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='sitio.tratamiento', verbose_name='tratamiento')),
            ],
            options={
                'verbose_name': 'solicitud de cita',
                'verbose_name_plural': 'solicitudes de cita',
                'ordering': ['-creada'],
            },
        ),
    ]
